# Generated by Django 2.2.14 on 2020-09-28 09:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('igrac', '0003_manualpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreference',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('manual_page_link', models.CharField(blank=True, help_text='Link to manual page', max_length=100)),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
    ]
