# Generated by Django 2.2.14 on 2020-10-12 07:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('igrac', '0004_sitepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.TextField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('upload_file', models.FileField(null=True, upload_to='upload-file/')),
                ('is_processed', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_session_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Session',
                'verbose_name_plural': 'Upload Sessions',
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
