# Generated by Django 2.2.12 on 2020-12-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrac', '0004_sitepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapslugmapping',
            name='featured',
            field=models.BooleanField(default=False, help_text='Should this resource be showed in home page?', verbose_name='Featured'),
        ),
    ]
