# Generated by Django 2.2.12 on 2020-12-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrac', '0005_mapslugmapping_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapslugmapping',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='mapslugmapping',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
