# Generated by Django 2.2.28 on 2022-10-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrac', '0007_igracprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='igracprofile',
            name='organization_types',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Type of organization'),
        ),
    ]
