# Generated by Django 3.2.16 on 2023-06-05 06:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0044_alter_dataset_unique_together'),
        ('igrac', '0008_igracprofile_organization_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundwaterLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisations', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.dataset')),
            ],
        ),
    ]
