# Generated by Django 3.2.16 on 2023-06-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igrac', '0009_auto_20230605_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groundwaterlayer',
            options={'verbose_name': 'Well and monitoring data layer', 'verbose_name_plural': 'Well and monitoring data layers'},
        ),
    ]
