# Generated by Django 3.2.20 on 2024-02-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrac', '0010_alter_groundwaterlayer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreference',
            name='download_readme_text',
            field=models.TextField(blank=True, help_text='Readme text to be included in the download zip  file.', null=True),
        ),
    ]
