# Generated by Django 3.2.20 on 2024-03-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrac', '0011_registrationpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreference',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
