# Generated by Django 3.2.20 on 2024-03-01 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igrac', '0011_auto_20240229_0431'),
        ('igrac', '0011_registrationpage'),
    ]

    operations = [
    ]
