# Generated by Django 3.2.20 on 2024-03-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrac', '0013_auto_20240322_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundwaterlayer',
            name='is_ggmn_layer',
            field=models.BooleanField(default=False, help_text='Indicate that this layer is ggmn layer. It will be used to construct the data to be downloaded.'),
        ),
    ]
