# Generated by Django 3.2.20 on 2025-02-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrac', '0014_groundwaterlayer_is_ggmn_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreference',
            name='well_and_monitoring_data_layer_sql',
            field=models.TextField(default='\n            select \n                id, ggis_uid, original_id, name, feature_type,purpose, \n                status, organisation,\n                 \n                number_of_measurements_level as "groundwater_level_data", \n                number_of_measurements_quality as "groundwater_quality_data", \n                number_of_measurements_yield as "abstraction_discharge",\n                \n                country, year_of_drilling, aquifer_name, aquifer_type,manager, \n                detail, location, \n                created_at, created_by, last_edited_at, last_edited_by,\n                \n                first_time_measurement,\n                last_time_measurement,\n                is_groundwater_level,\n                is_groundwater_quality \n             from {table} \n             where organisation_id IN ({organisations}) \n             order by created_at DESC        \n        '),
        ),
    ]
