# Generated by Django 4.2.17 on 2025-07-01 06:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0044_alter_dataset_unique_together"),
        ("maps", "0043_auto_20230807_1234"),
        ("igrac", "0015_sitepreference_well_and_monitoring_data_layer_sql"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeonodePage",
            fields=[
                (
                    "blogpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="igrac.blogpage",
                    ),
                ),
                (
                    "datasets",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="layers.dataset"
                    ),
                ),
                (
                    "maps",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="maps.map"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("igrac.blogpage",),
        ),
    ]
