# Generated by Django 4.2.17 on 2025-07-02 04:09

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("geoapps", "0006_geoapp_blob_migration"),
        ("documents", "0038_alter_document_doc_url"),
        ("igrac", "0016_geonodepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="geonodepage",
            name="documents",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="documents.document"
            ),
        ),
        migrations.AddField(
            model_name="geonodepage",
            name="geostories",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="geoapps.geoapp"
            ),
        ),
    ]
