# Generated by Django 4.2.17 on 2025-07-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "igrac",
            "0018_rename_ggmn_download_readme_text_sitepreference_legacy_ggmn_download_readme_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="groundwaterlayer",
            name="additional_sql",
            field=models.TextField(
                blank=True,
                help_text="Additional sql that will be added to the sql that will be used to filter the well data.",
            ),
        ),
        migrations.AlterField(
            model_name="sitepreference",
            name="well_and_monitoring_data_layer_sql",
            field=models.TextField(
                default='\n                select id,\n                       ggis_uid,\n                       original_id,\n                       name,\n                       feature_type,\n                       purpose,\n                       status,\n                       organisation,\n\n                       number_of_measurements_level   as "groundwater_level_data",\n                       number_of_measurements_quality as "groundwater_quality_data",\n                       number_of_measurements_yield   as "abstraction_discharge",\n\n                       country,\n                       year_of_drilling,\n                       aquifer_name,\n                       aquifer_type,\n                       manager,\n                       detail,\n                       location,\n                       created_at,\n                       created_by,\n                       last_edited_at,\n                       last_edited_by,\n\n                       first_time_measurement         as first_recorded_measurement,\n                       last_time_measurement          as last_recorded_measurement,\n                       is_groundwater_level           as groundwater_level,\n                       is_groundwater_quality         as groundwater_quality,\n                       ground_surface_elevation,\n                       ground_surface_elevation_unit,\n                       dem_elevation,\n                       dem_elevation_unit\n                from {table}\n                where organisation_id IN ({organisations}) {additional_sql}\n                order by created_at DESC\n                '
            ),
        ),
    ]
