# Generated by Django 4.2.17 on 2026-06-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("igrac", "0019_groundwaterlayer_additional_sql_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitepreference",
            name="legacy_ggmn_download_readme_text",
        ),
        migrations.AddField(
            model_name="sitepreference",
            name="help_page_url",
            field=models.URLField(
                blank=True,
                default="https://kartoza.github.io/IGRAC-GGIS/tutorial/",
                help_text="Link to help page url from github docs. It will do crawling from the page and show it as popup.",
                null=True,
            ),
        ),
    ]
