# Generated by Django 4.2.17 on 2026-08-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "igrac",
            "0020_remove_sitepreference_legacy_ggmn_download_readme_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sitepreference",
            name="dashboard_ggmn_popup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dashboard_ggmn_popup",
                to="igrac.geonodepage",
            ),
        ),
        migrations.AddField(
            model_name="sitepreference",
            name="dashboard_repository_popup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dashboard_repository_popup",
                to="igrac.geonodepage",
            ),
        ),
    ]
