# Generated by Django 3.2.16 on 2023-06-07 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('api_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_write', models.BooleanField(default=False, help_text='Allow this api key to write data.')),
                ('max_request_per_day', models.IntegerField(blank=True, help_text='Max request per day for the api key. Keep blank or null for unlimited.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeyRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=126)),
                ('time', models.DateTimeField()),
                ('url', models.TextField()),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrac_api.apikey')),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeyAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('counter', models.IntegerField(default=0)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrac_api.apikey')),
            ],
        ),
    ]
