# Generated by Django 3.2.16 on 2023-06-07 08:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiKey',
            fields=[
                ('api_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('allow_write', models.BooleanField(default=False, help_text='Allow this api key to write data')),
                ('max_request_per_day', models.IntegerField(default=1000, help_text='Max request per day for the api key.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeyRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=126)),
                ('time', models.DateTimeField()),
                ('url', models.TextField()),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrac_api.userapikey')),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeyEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=512)),
                ('contact_email', models.EmailField(max_length=254)),
                ('organisation_name', models.CharField(max_length=512)),
                ('organisation_url', models.CharField(max_length=512, validators=[django.core.validators.URLValidator()])),
                ('project_url', models.CharField(help_text='web site or project URL for API will be used', max_length=512, validators=[django.core.validators.URLValidator()])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False, help_text='When approved, the api_key will be created and activated')),
                ('api_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='igrac_api.userapikey')),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeyAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('counter', models.IntegerField(default=0)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igrac_api.userapikey')),
            ],
        ),
    ]
