#--------- Generic stuff all our Dockerfiles should start with so we get caching ------------
FROM kartoza/sadc_gip:geoserver-3.1
MAINTAINER Irwan <irwan@kartoza.com>

ADD deployment/geoserver/plugins/* /geoserver/webapps/geoserver/WEB-INF/lib/