name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        
      - name: Create Mkdocs Config 🚀
        working-directory: ./docs
        run: ./create-mkdocs-html-config.sh   
        
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir mkdocs-material mkdocs-video qrcode


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site