# GeoHosting Controller.
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ggis_app_test:
    name: 'GGIS App'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Free disk space
        run: |
          echo "Cleaning up disk space on GitHub runner..."
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo apt-get clean
          df -h
      - name: Cleanup Docker
        if: always()
        run: |
          docker container prune -f
          docker image prune -af
          docker volume prune -f
      - name: Run docker-compose services
        working-directory: deployment
        run: |
          echo "Override docker-compose for testing purposes"
          cp docker-compose.override.template.yml docker-compose.override.yml
          make dev
          make wait-db
          make sleep

      - name: Test backend
        run: make dev-test